services:
  - type: web
    name: ed3s-map-2026
    runtime: static
    branch: main
    buildCommand: ./build.sh
    staticPublishPath: ./output
    autoDeployTrigger: commit
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
